function loadEditor(noreset){editorClose();if(!noreset){window.canedit=true;setMap(["Special","Blank"]);window.canedit=false;}
setEditorLibrary();setEditorHTML();setEditorControls();setEditorTriggers();setEditorLocalRetrieval();classAdd(body,"editor");classAdd(editor.sidebar,"expanded");TimeHandler.addEvent(classRemove,35,editor.sidebar,"expanded");map.shifting=false;window.editing=true;}
function setEditorLibrary(){window.editor={xloc:0,yloc:0,playing:false,canplace:true,offset:{x:unitsizet2},settings:{night:false,setting:"Overworld",alt:false},defaults:{width:8,height:8,widthoff:0,heightoff:0,minimum:1,followerUpdate:editorFollowerUpdateStandard,prefunc:pushPreThing,outerok:true},placed:[],characters:{Goomba:{},Koopa:{height:12,arguments:{smart:Boolean,movement:["moveSimple","moveJumping","moveFloating"]},followerUpdate:function(reference,pairs){var smart=pairs.smart=="True",fname=pairs.movement,func=fname=="moveJumping";if(fname=="moveFloating")func=[8,72];return[smart,func];},onadds:{nocollide:false}},Beetle:{width:8.5,height:8.5},HammerBro:{height:12},CheepCheep:{arguments:{smart:Boolean},attributes:{nofall:true}},Lakitu:{height:12},Podoboo:{width:7},Blooper:{height:12,onadds:{nofall:true}},Bowser:{width:16,height:16}},solids:{Floor:{arguments:{width:8},mydefaults:{width:8},prefunc_custom:function(prestatement,placer,reference,args){var output="Floor, "+prestatement.xloc+", "+(prestatement.yloc);if(args[1])output+=", "+args[1];return output;}},Brick:{arguments:{contents:["false","Coins","Star"]},followerUpdate:function(reference,pairs){var output=[],content=pairs.contents;output.push(window[pairs.contents]);return output;},prefunc_custom:function(prestatement,placer,reference,args){var output="Brick, ";output+=prestatement.xloc+", "+(prestatement.yloc);if(placer.contents){output+=", "+placer.contents[0].name;}
return output;}},Block:{arguments:{contents:["Coin","Mushroom","Star","1Up Mushroom"],hidden:Boolean},followerUpdate:function(reference,pairs){var output=[],content=pairs.contents;if(content=="1Up Mushroom")output.push([Mushroom,1]);else output.push(window[pairs.contents]);if(pairs.hidden=="True"){TimeHandler.addEvent(function(){editor.follower.hidden=true;});output.push(1);}
return output;},prefunc_custom:function(prestatement,placer,reference,args){var output="Block, ",contents=placer.contents,contained=contents[0].name;output+=prestatement.xloc+", "+prestatement.yloc;if(contained!="Coin"){if(contained=="Mushroom"&&contents[1]){output+=", [Mushroom, "+String(contents[1])+"]";}
else output+=", "+contained;if(placer.hidden)output+=", true";}
else if(placer.hidden)output+=", false, true";return output;}},Cannon:{arguments:{height:8},sprite_source:"top"},Pipe:{width:16,prefunc:pushPrePipe,prefunc_solo:true,arguments:{height:8,Pirhana:Boolean},followerUpdate:function(reference,pairs){var output=[];output.push(Number(pairs.height));output.push(Boolean(pairs.Pirhana));return output;},sprite_source:"top"},Stone:{arguments:{width:8,height:8},prefunc_custom:function(prestatement,placer,reference,args){var output="Stone, "+prestatement.xloc+", "+(prestatement.yloc);output+=", "+args[1]+", "+args[2];return output;}},Coral:{arguments:{height:8}},CastleBlock:{arguments:{fireballs:2,direction:["CW","CCW"],hidden:Boolean},followerUpdate:function(reference,pairs){var length=Number(pairs.fireballs),dt=pairs.direction=="CW",hidden=pairs.hidden=="True";return[[length,dt],hidden];}},Springboard:{height:14.5,heightoff:1.5}},scenery:{Bush1:{width:16},Bush2:{width:24},Bush3:{width:32},Cloud1:{width:16,height:12},Cloud2:{width:24,height:12},Cloud3:{width:32,height:12},HillSmall:{width:24,height:9.5,heightoff:-1.5},HillLarge:{width:40,height:17.5,heightoff:-1.5},PlantSmall:{width:7,height:15,heightoff:1},PlantLarge:{height:23,heightoff:1},Fence:{},Water:{width:4,height:4,prefunc:fillPreWater,prefunc_solo:true,prefunc_custom:function(prestatement,placer,reference,args){return prestatement.xloc+", "+(prestatement.yloc);}}}};var load_paths={},defaults=editor.defaults,group,me,locj,i,j;for(i in editor){group=editor[i];for(j in editor[i]){me=group[j];proliferate(me,editor.defaults,true);}}
group=editor.scenery;for(i in group){me=group[i];proliferate(me,{createfunc:function(me){return ThingCreate(Sprite,me.spritename);},spritename:i,prefunc_custom:function(prestatement,placer,reference,args){return "'"+reference.spritename+"', "+prestatement.xloc+", "+(prestatement.yloc-reference.height);}},true);if(me.prefunc==pushPreThing)me.prefunc=pushPreScenery;}}
function setEditorHTML(){createEditorGuideLines();createEditorSidebar();createEditorBottomBar();createEditorScrollers();editor.sectionselect.onchange();}
function createEditorSidebar(){var optionNames=["Solids","Characters","Scenery","Settings"],sidebar=editor.sidebar=createElement("div",{id:"sidebar"}),category=editor.category=createElement("div",{id:"category",className:"group first"}),sectionselect=editor.sectionselect=createElement("select",{id:"sectionselect",className:"options big",onchange:editorSelectSection}),options=editor.options=createElement("div",{id:"options",className:"options big"}),i;sidebar.appendChild(category);category.appendChild(sectionselect);for(i in optionNames){sectionselect.appendChild(createElement("option",{innerText:optionNames[i]}));}
sidebar.appendChild(options);body.appendChild(window.sidebar=sidebar);}
function createEditorBottomBar(){var bar=editor.bottombar=createElement("div",{id:"bottombar",things:{}});sidebar.appendChild(bar);}
function createEditorScrollers(){var names=["right","left"],scrollers={},name,i,parent,div,top;parent=createElement("div",{id:"scrollers",style:{zIndex:7,width:(innerWidth-32)+"px"}});settings={className:"scroller",style:{zIndex:7,marginTop:innerHeight/2+"px"},onmouseover:editorFollowerHide,onmouseout:editorFollowerShow,onmousedown:editorScrollingStart,onmouseup:editorScrollingStop};for(i=names.length-1;i>=0;--i){name=names[i];div=scrollers[names[i]]=createElement("div",settings);parent.appendChild(div);}
proliferate(scrollers["left"],{id:"left",className:"scroller flipped off",dx:-7});proliferate(scrollers["right"],{id:"right",style:{right:"21px"},dx:7});editor.scrollers=scrollers;body.appendChild(parent);}
function editorFollowerHide(){var follower=editor.follower;follower.hiddenOld=follower.hidden;follower.hidden=true;}
function editorFollowerShow(){var follower=editor.follower;follower.hidden=follower.hiddenOld;}
function editorScrollingStart(event){var scroller=event.target,dx=scroller.dx;editorPreventClicks();editor.scrolling=TimeHandler.addEventInterval(editorScrolling,1,Infinity,-dx);classRemove(editor.scrollers["left"],"off");}
function editorScrollingStop(){TimeHandler.addEvent(editorClickOff,3);TimeHandler.clearEvent(editor.scrolling);}
function editorScrolling(dx){scrollEditor(dx);if(editor.xloc>=0){scrollEditor(-editor.xloc);editorScrollingStop();classAdd(editor.scrollers["left"],"off");return true;}}
function createEditorGuideLines(){var lines={floor:0,ceiling:ceillev,jumplev1:jumplev1,jumplev2:jumplev2},left=16*unitsize+"px",floor=map.floor,i,parent,line;window.maplines=parent=document.createElement("div");parent.style.marginLeft=left;parent.id="maplines";for(i in lines){line=createElement("div",{innerText:i,className:"mapline",id:i+"_line",style:{marginTop:(floor-lines[i])*unitsize+"px",marginLeft:"-"+left,paddingLeft:left}});parent.appendChild(line);}
body.appendChild(parent);}
function setEditorControls(names){names=names||["load","save","reset","undo"];var previous=document.getElementById("controls"),container=createElement("div",{id:"controls"}),controls=editor.controls={container:container},name,div,i;if(previous)previous.innerHTML="";for(i in names){name=names[i];div=createElement("div",{id:name,alt:name,className:"control",style:{backgroundImage:"url(Theme/"+name+".gif)"},innerHTML:"<div class='controltext'>"+name+"</div>",onclick:editorClickControl});container.appendChild(div);controls[name]=div;}
sidebar.appendChild(container);}
function setEditorTriggers(){var activators=[maplines,canvas],me,i;for(i=activators.length-1;i>=0;--i){me=activators[i];me.onclick=editorMouseClick;}
document.onmousemove=editorFollowerFollowsCursor;}
function editorMouseClick(event){if(!window.editing||editor.clicking)return;editorPreventClicks();if(editor.erasing)return editorPlaceEraser(event);if(editor.in_settings||!editor.canplace)return;var section_name=editor.section_name,current_section=window[section_name],thing_name=editor.current_selected,follower_old=editor.follower;editor.placed.push(follower_old);editor.follower=false;editorSetCurrentThingFromName(null,true);if(paused)refillCanvas();follower_old.was_follower=true;delete follower_old.onclick;if(editor.playing){thingRetrieveVelocity(follower_old);proliferate(follower_old,follower_old.reference.attributes);}}
function editorSelectSection(){var selected=(this||editor.sectionselect).value.toLowerCase();if(editor.in_settings=selected=="settings"){editorSetSection(selected,true);editorSetSectionSettings();}
else editorSetSection(selected);}
function editorSetSection(name,nothing){var section=editor.section=editor[name],bottombar=editor.bottombar,num_kids=0,canv_sel,canv,first,name;editor.section_name=name;bottombar.innerHTML="";if(!nothing){for(name in section){++num_kids;canv=editorAddBottomPreview(bottombar,name,section[name]);if(!canv_sel)
canv_sel=canv;}}
if(num_kids){bottombar.style.visibility="visible";editorSetCurrentThingFromCanvas(canv_sel);}
else bottombar.style.visibility="hidden";}
function editorAddBottomPreview(bottombar,name,ref){var width=ref.width,height=ref.height,thingfunc=window[name],thing=thingfunc?ThingCreate(thingfunc,ref.previewargs):new Thing(Sprite,name),holder=createElement("div",{width:width*unitsize+"px",height:height*unitsize+"px",name:name,className:"holder "+name,onclick:editorSetCurrentThing}),maxWidth={maxWidth:"100%"},maxHeight={maxHeight:"100%"},canvas=proliferate(getCanvas(width*unitsizet2,height*unitsizet2),{name:name,reference:ref,style:{marginLeft:-roundDigit(width/2,scale)+"px"},onclick:editorSetCurrentThing}),things=bottombar.things,sizewidth=width*unitsizet2,sizeheight=height*unitsizet2,context=canvas.getContext("2d"),csource;canvasDisableSmoothing(canvas);editor.bottombar.things[name]=canvas.thing=thing;addClass(thing,"editor");csource=thing.canvas;if(thing.canvases)csource=thing.canvases[ref.sprite_source||"middle"].canvas;if(ref.previewsize){context.fillStyle=context.createPattern(csource,"repeat");context.fillRect(0,0,sizewidth,sizeheight);}
else{context.drawImage(csource,0,0,sizewidth,sizeheight);}
holder.appendChild(holder.canvas=canvas);bottombar.appendChild(holder);bottombar[name]=holder;return canvas;}
function editorSetSectionSettings(){var settings=editor.settings,html="<table>",rows;html+="<h3 class='title'>Settings</h3>";html+=addArgumentOption("night",Boolean,settings.night);html+=addArgumentOption("setting",["Overworld","Underworld","Underwater","Castle","Sky"],settings.setting);html+=addArgumentOption("alt",Boolean,settings.alt);html+="</table>";options.innerHTML=html;ensureOptionsAboveZero(editorUpdateSettingsOption);rows=editor.sidebar.getElementsByTagName("table")[0].rows;editor.settings.night_elem=rows[0].cells[1].firstChild;editor.settings.setting_elem=rows[1].cells[1].firstChild;editor.settings.alt_elem=rows[2].cells[1].firstChild;if(editor.follower)killNormal(editor.follower);editor.follower=false;}
function editorUpdateSettingsOption(event){var settings=editor.settings,night=settings.night=settings.night_elem.value=="True",alt=settings.alt=settings.alt_elem.value=="True",setting=settings.setting=settings.setting_elem.value,newsetting=setting+(night?" Night":"")+(alt?" "+alt:"");setAreaSetting(area,newsetting,newsetting!=area.setting);}
function editorSetCurrentThing(event,sameargs){var self=event.target,name=editor.current_thing_name=self.name,refs=editor.current_thing=editor.section[name];if(!sameargs)updateCurrentArguments(name,refs);editorUpdateFollower();}
function editorSetCurrentThingFromCanvas(canv,sameargs){editorSetCurrentThing({target:canv},sameargs);}
function editorSetCurrentThingFromName(name,sameargs){editorSetCurrentThing({target:{name:name||editor.current_thing_name}},sameargs);}
function updateCurrentArguments(name,reference){reference=reference||{};var options=editor.options,html="<table>",mydefaults=reference.mydefaults||{},arguments=reference.arguments||{},i;html+="<h3 class='title'>"+name+"</h3>";if(!arguments.width)html+=addStaticOption("width",reference.width);if(!arguments.height)html+=addStaticOption("height",reference.height);for(i in arguments){html+=addArgumentOption(i.replace("_","-"),arguments[i],null,mydefaults);}
html+="</table>";options.innerHTML=html;ensureOptionsAboveZero();}
function addStaticOption(name,value){if(value==Infinity)value="Inf.";return "<tr id='option_"+name+"' class='auto'><td>"+name+": </td><td class='auto'>"+value+"</td></tr>";}
function addArgumentOption(name,value,ref,mydefaults){mydefaults=mydefaults||{};var text="<tr name='"+name+"' id='option_"+name+"'><td>"+name+": </td><td>";switch(value){case Infinity:text+="Inf";break;case Boolean:text+="<select name='"+name+"' value='"+(value?"true":"false")+"'><option>False</option><option>True</select>";break;case Number:text+="<input name='"+name+"' value='"+String(value||0)+"' type='Number'>";break;default:switch(typeof(value)){case "number":text+="<span class='optspan'>"+value+"x</span><input name='"+name+"' type='Number' class='text' value='"+(mydefaults[name]||1)+"'>";break;case "string":text+="<input name='"+name+"' type='text' class='text wide' value='"+value+"'>";break;case "object":text+="<select name='"+name+"'>";for(i in value)text+="<option>"+value[i]+"</option>";text+="<select>";break;}
break;}
return text+"</td></tr>";}
function ensureOptionsAboveZero(updatefunc){updatefunc=updatefunc||editorUpdateFollower;var elements=editor.options.getElementsByTagName("input"),element;for(i=elements.length-1;i>=0;--i){element=elements[i];element.onchange=element.onclick=element.onkeypress=editorInputEnsureAboveZero;}
elements=options.getElementsByTagName("select");for(i=elements.length-1;i>=0;--i){element=elements[i];element.onchange=element.onclick=element.onkeypress=editorUpdateFollower;}}
function editorInputEnsureAboveZero(event){editorUpdateFollower(event);}
function editorUpdateFollower(event){if(editor.in_settings)return editorUpdateSettingsOption(event);var current_thing=editor.current_thing,args,follower;if(follower=editor.follower){follower.id="";killNormal(follower);}
if(current_thing.createfunc){follower=current_thing.createfunc(editor.current_thing,editorGetArguments());}
else follower=ThingCreate(window[editor.current_thing_name],current_thing.followerUpdate(editor.current_thing,editorGetArguments()));editor.follower=follower;proliferate(follower,{id:"follower",libtype:editor.section_name,lookleft:true,nocollide:true,reference:current_thing,onclick:editorMouseClick},true);addThing(follower);addClass(follower,"editor");thingRetrieveVelocity(follower);thingStoreVelocity(follower);editorSetFollowerPosition(follower);if(editor.erasing)follower.hidden=true;}
function editorGetArguments(){var inputs=arrayMake(editor.options.getElementsByTagName("input")),selects=arrayMake(editor.options.getElementsByTagName("select")),combined=inputs.concat(selects);pairs=generateInputNameValuePairs(combined);return pairs;}
function generateInputNameValuePairs(inputs){var output={},i;for(i in inputs){output[inputs[i].name]=inputs[i].value;}
return output;}
function editorFollowerFollowsCursor(event){var follower=editor.follower;if(!follower)return;var xloc=roundFollowerDigit(event.x)+(editor.current_thing.widthoff-editor.offset.x)*unitsize,yloc=roundFollowerDigit(event.y)+editor.current_thing.heightoff*unitsize;editorSetFollowerPosition(follower,xloc,yloc);}
function editorSetFollowerPosition(follower,xloc,yloc){xloc=xloc||editor.xloc_old||0;yloc=yloc||editor.yloc_old||0;setLeft(follower,xloc);setTop(follower,yloc);editor.xloc_old=xloc;editor.yloc_old=yloc;}
function roundFollowerDigit(num){var diff=editor.section_name=="solids"?8:4;return unitsize*diff*round(num/(unitsize*diff));}
function roundFollowerPosition(me,num){editorSetFollowerPosition(me,roundFollowerDigit(me.left),roundFollowerDigit(me.top));}
function editorFollowerUpdateStandard(reference,pairs){if(pairs.hidden=="True"){TimeHandler.addEvent(function(){editor.follower.hidden=true;});}
var output=[];if(pairs.width)output.push(Number(pairs.width));if(pairs.height)output.push(Number(pairs.height));return output;}
function editorClickControl(event){editorPreventClicks();var target=event.target;if(!target.id)target=target.parentNode;window["editorControl"+capitalizeFirst(target.id)]();event.preventDefault();}
function editorPreventClicks(){editor.clicking=true;TimeHandler.addEvent(editorClickOff,3);}
function editorClickOff(){if(window.editor)editor.clicking=false;}
function editorControlUndo(){var placed=editor.placed,last=placed.pop();if(last&&!last.player){killNormal(last);}}
function editorControlReset(){var placed=editor.placed,len=placed.length,timer=roundDigit(35/len,21);TimeHandler.addEventInterval(editorControlUndo,timer,len);}
function editorControlSave(){var rawfunc=editor.rawfunc=editorGetRawFunc(),title="<span style='font-size:1.4em;'>Hit Submit below to start playing!</span>",p="<p style='font-size:.7em;line-height:140%'>This map will be resumed automatically the next time you use the editor on this computer.<br>Alternately, you may copy this text to work on again later using Load (the button next to Save). </p>",menu=editorCreateInputWindow(title+"<br>"+p,rawfunc,editorSubmitGameFuncPlay);return rawfunc;}
function editorControlCancel(){loadEditor();}
function editorGetRawFunc(){var placed=editor.placed,lenm1=placed.length-1,statements=new Array(i),rawfunc="  var map = arguments[0] || new Map();\n",i;rawfunc+="\n  map.time = "+data.time.amount+";";rawfunc+="\n  map.locs = [ new Location(0, true) ];";rawfunc+="\n  map.areas = [";rawfunc+="\n    new Area('"+area.setting+"', function() {";rawfunc+="\n      setLocationGeneration(0);\n\n";for(i=lenm1;i>=0;--i){statements[i]=new editorPreStatement(placed[i]);}
statements.sort(prethingsorter);for(i=lenm1;i>=0;--i){statements[i]="      "+statements[i].statement;}
statements=removeDuplicates(statements);rawfunc+=statements.join("\n");rawfunc+="\n    })";rawfunc+="\n  ];";rawfunc+="\n  return map;"
return rawfunc;}
function editorPreStatement(placer){this.placer=placer;this.xloc=(gamescreen.left+placer.left)/unitsize;this.yloc=map.floor-placer.top/unitsize;this.statement=editorGetStatement(this,placer,placer.reference,placer.args);}
function editorGetStatement(prestatement,placer,reference,args){if(!reference){reference=editor[placer.libtype][placer.title];if(!reference)return "";}
var statement=(reference.prefunc||pushPreThing).name,numargs=args.length,argstrings,arg;if(reference.prefunc_custom){statement+="("+reference.prefunc_custom(prestatement,placer,reference,args)+");";}
else{argstrings=[];if(!reference.prefunc_solo)argstrings.push(placer.title);argstrings.push(String(prestatement.xloc));argstrings.push(String(prestatement.yloc));for(var i=1;i<numargs;++i){switch(typeof(arg=args[i])){case "undefined":break;case "number":arg=String(round(arg));break;default:arg=String(arg);break;}
if(typeof(arg)!="undefined")
argstrings.push(arg);}
statement+="("+argstrings.join(", ")+");";}
return statement;}
function editorControlErase(){!editor.erasing?editorControlEraseOn():editorControlEraseOff();}
function editorControlEraseOn(){editor.erasing=editor.follower.hidden=true;classAdd(body,"erasing");classAdd(editor.controls.erase,"enabled");}
function editorControlEraseOff(){editor.erasing=editor.follower.hidden=false;classRemove(body,"erasing");classRemove(editor.controls.erase,"enabled");}
function editorPlaceEraser(event){addThing(Eraser,event.x,event.y);}
function Eraser(me){me.width=me.height=2;me.nocollide=me.nofall=true;me.movement=eraserErases;setCharacter(me,"eraser");}
function eraserErases(me){if(!window.editor)return;var placed=editor.placed,arr=placed.concat(solids).concat(characters).concat(scenery),other,i;for(i=arr.length-1;i>=0;--i){other=arr[i];if(other.player||other==editor.follower)continue;if(objectsTouch(me,other)){killNormal(other);placed.splice(placed.indexOf(other),1);break;}}
killNormal(me);}
function editorControlLoad(){var blurb="Paste your work in progress here, and click Submit to continue it.";editorCreateInputWindow(blurb,"",editorSubmitLoad);}
function addThingsToPlaced(){var placed=editor.placed;editor.placed=(editor.placed||[]).concat(characters).concat(solids).concat(scenery);placed.sort(prethingsorter);placed.splice(placed.indexOf(player),1);for(i=placed.length-1;i>=0;--i){placer=placed[i];placer.reference=editor[placer.libtype][placer.title];}}
function editorCreateInputWindow(blurb,value,callback){var bigwidth=gamescreen.unitwidth,div=editor.input_window=createElement("div",{id:"input_window",innerHTML:blurb||"",style:{width:bigwidth+"px"}}),input=div.input=editor.window_input=createElement("textarea",{id:"window_input",value:value||"",style:{width:(bigwidth-49)+"px"}}),submit=div.submit=createElement("div",{id:"window_submit",className:"window_button",innerText:"Submit",onclick:callback}),cancel=div.cancel=createElement("div",{id:"window_cancel",className:"window_button",innerText:"Cancel",onclick:editorCloseInputWindow});div.appendChild(input);div.appendChild(submit);div.appendChild(cancel);body.appendChild(div);killNormal(editor.follower=false);editor.follower=false;return div;}
function editorCloseInputWindow(noedit){editorPreventClicks();removeChildSafe(window.input_window,body);if(!noedit){editorSetCurrentThingFromName();window.editing=true;}
editorUpdateFollower();}
function editorClose(inmap){if(!window.editor)return;classRemove(body,"editor");classRemove(body,"erasing");killNormal(editor.follower);editor.follower=false;delete window.editor;var ids=["maplines","sidebar","bottombar","scrollers"],i;for(i in ids)removeChildSafe(document.getElementById(ids[i]),body);document.onmousemove=null;window.editing=false;if(inmap&&window.map)map.shifting=false;}
function scrollEditor(xinv,yinv){if(!window.editor)return;var follower=editor.follower;if(!follower)return;xinv=xinv||0;yinv=yinv||0;shiftAll(scenery,xinv,yinv);shiftAll(solids,xinv,yinv);shiftAll(characters,xinv,yinv);editor.xloc+=xinv;editor.yloc+=yinv;}
function editorStoreLocally(){localStorage.editorLastFunc=editor.rawfunc;}
function setEditorLocalRetrieval(){var found=localStorage.editorLastFunc;if(!found)return;editor.rawfunc=round;editorSubmitGameFunc();}
function editorSubmitGameFunc(){if(!window.editor||!editor.rawfunc)return loadEditor();var rawfunc=editor.rawfunc,mapfunc=window.custommapfunc=new Function(editor.rawfunc);mapfuncs.Custom={Map:mapfunc};window.canedit=true;setMap(["Custom","Map"]);window.canedit=editor.playing=false;entryBlank(player);addThingsToPlaced();editorStoreLocally();editorCloseInputWindow();}
function editorSubmitGameFuncPlay(){editorPreventClicks();editorSubmitGameFunc();editorStartPlaying();}
function editorSubmitLoad(){if(!window.editor||!editor.window_input)return;editorPreventClicks();var rawfunc=editor.window_input.value;loadEditor();editor.rawfunc=rawfunc;editorSubmitGameFunc();}
function editorStartPlaying(){editorPreventClicks();editor.playing=true;placePlayer();entryPlain(player);nokeys=false;var placed=editor.placed,placer,ref,i;for(i in placed){placer=placed[i];thingRetrieveVelocity(placer);ref=editor[placer.libtype][placer.title];if(ref)
proliferate(placer,ref.onadds);}
setEditorControls(["Cancel"]);}
function setEditorLocalRetrieval(){var found=localStorage.editorLastFunc;if(!found)return;editor.rawfunc=found;editorSubmitGameFunc();editorStoreLocally();var placed=editor.placed,i;for(i in placed){thingStoreVelocity(placed[i]);}}