function TonedJS(give_window){var toned={giveSup:function(donor,recipient){recipient=recipient||{};for(var i in donor)
recipient[i]=donor[i];return recipient;},giveSub:function(donor,recipient){recipient=recipient||{};for(var i in donor)
if(!recipient.hasOwnProperty(i))
recipient[i]=donor[i];return recipient;},proliferate:function(recipient,donor,no_override){var setting,i;for(i in donor){if(no_override&&recipient.hasOwnProperty(i))continue;if(typeof(setting=donor[i])=="object"&&setting!=null){if(!recipient.hasOwnProperty(i))recipient[i]=setting instanceof Array?[]:{};proliferate(recipient[i],setting,no_override);}
else recipient[i]=setting;}
return recipient;},getFirst:function(obj,grabkey){for(var i in obj)return grabkey?i:obj[i];},getLast:function(obj,grabkey){for(var i in obj){}return grabkey?i:obj[i];},followPath:function(obj,path,num){if(path[num]!=null&&obj[path[num]]!=null)
return followPath(obj[path[num]],path,++num);return obj;},createElement:function(type){var elem=document.createElement(type||"div"),i=arguments.length;while(--i>0)
proliferate(elem,arguments[i]);return elem;},classAdd:function(me,strin){me.className+=" "+strin;},classRemove:function(me,strout){me.className=me.className.replace(new RegExp(" "+strout,"gm"),"");},elementSetPosition:function(me,left,top){if(left==undefined)left=me.left;if(top==undefined)top=me.top;proliferate(me,{left:left,top:top,style:{marginLeft:left+"px",marginTop:top+"px"}});},elementShiftLeft:function(me,left){if(!me.left)me.left=Number(me.style.marginLeft.replace("px",""));me.style.marginLeft=round(me.left+=left)+"px";},elementShiftTop:function(me,top){if(!me.top)me.top=Number(me.style.marginLeft.replace("px",""));me.style.marginTop=round(me.top+=top)+"px";},removeChildSafe:function(child,container){if(!child)return;container=container||document.body;if(container.contains(child))container.removeChild(child);},findParentOfType:function(child,type){var parent=child.parentElement;if(!parent||parent.nodeName==type)return parent;return findParentType(parent,type);},clearAllTimeouts:function(){var id=setTimeout(function(){});while(id--)clearTimeout(id);},stringTrim:function(me){return me.replace(/^\s+|\s+$/g,'');},stringOf:function(me,n){return(n==0)?'':new Array(1+(n||1)).join(me);},stringHas:function(haystack,needle){return haystack.indexOf(needle)!=-1;},stringHasI:function(haystack,needle){return haystack.toLowerCase().indexOf(needle.toLowerCase())!=-1;},capitalizeFirst:function(str,n){n=n||1;return str.substr(0,n).toUpperCase()+str.substr(n).toLowerCase();},ArrayD:function(dim){if(arguments.length==1)return new Array(dim);var rargs=arrayMake(arguments),me=new Array(dim),i;rargs.shift();for(i=dim-1;i>=0;--i){me[i]=ArrayD.apply(this,rargs);}
return me;},arrayOf:function(me,n){n=n||1;var arr=new Array(n);while(n--)arr[n]=me;return arr;},arrayMake:function(me){return Array.prototype.slice.call(me);},arrayRange:function(a,b){var len=1+b-a,arr=new Array(len),val=a,i=0;while(i<len)arr[i++]=val++;return arr;},arrayShuffle:function(arr,start,end){start=start||0;end=end||arr.length;for(var i=start,temp,sloc;i<=end;++i){sloc=randInt(i+1);temp=arr[i];arr[i]=arr[sloc];arr[sloc]=temp;}
return arr;},removeDuplicates:function(arr){var output=[],me,hasdup,len,i,j;for(i=0,len=arr.length;i<len;++i){me=arr[i];hasdup=false;for(j=0;j<i;++j){if(arr[j]==me){hasdup=true;break;}}
if(!hasdup)output.push(me);}
return output;},makeDigit:function(num,size,fill){num=String(num);return stringOf(fill||0,max(0,size-num.length))+num;},roundDigit:function(n,d){return Number(d?~~(0.5+(n/d))*d:round(n));},sign:function(n){return n?n<0?-1:1:0;},round:function(n){return~~(0.5+n);},max:Math.max,min:Math.min,abs:Math.abs,pow:Math.pow,ceil:Math.ceil,floor:Math.floor,random:Math.random,randInt:function(n){return floor(Math.random()*(n||1));},signBool:function(n){return n>0?true:false;},log:console.log.bind(console),now:Date.now};if(give_window)toned.giveSub(toned,window);return toned;}